cloud:
  cloud_return_variables:
    - time_sent
    - temp
    - internal_resistance
    - p 
    - innovation
  send_cloud_variables:
    - time_sent
    - temp
    - temp_prev
    - current
    - cooling_power
    - dt
    - internal_resistance
    - p
  warmup_period: 20
  

can:
  bitrate: 500000
  dbc: PiCAN.dbc
  rbat_initial: 0.002

rls:
  covariance: 0.001
