cloud:
  cloud_return_variables:
    - time_sent
    - temp
    - internal_resistance
    - p 
    - innovation
  send_cloud_variables:
    - time_sent
    - temp
    - temp_prev
    - current
    - cooling_power
    - dt
    - internal_resistance
    - p
  warmup_period: 20
  

can:
  bitrate: 500000
  dbc: PiCAN.dbc

rls:
  internal_resistance: 0.0020664
  covariance: 1